name: 'Hello World'
description: 'Hello 1,2'
runs:
  using: "composite"
  steps:
    - name: hello 1
      run: echo "{${{ secrets.HOGE }}"
      shell: bash
    - name: hello 2
      run: echo "{${{ secrets.FUGA }}"
      shell: bash
