name: Go
on: [push]
jobs:

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: test
      run: go test ./... -v

    - name: Build
      run: go build -v .
      
    - name: print!
      run: echo "github ref; ${{ github.ref }}, base_ref; ${{github.ref#refs/heads/}}"
        
