name: Go
on: push
   
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/github-script@v6
      with:
         script: |
            core.setFailed('失敗させてみる')
    
    - name: check github
      run: |
        echo 'event: ${{ toJSON(github) }}'
        
    - name: check secrets
      run: |
        curl -X GET ${{ secrets.URL }}

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: test
      run: go test ./... -v

    - name: Build
      run: go build -o artifact -v .
      
    - name: print!
      run: echo "github ref; ${{ github.ref }}, base_ref; ${GITHUB_REF#refs/heads/}"
      
    - name: steps action
      uses: ./.github/steps_action

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: artifact
