on:
  pull_request:
     types: [opened, edited, synchronize, rerequested]
name: Danger Pull Request
jobs:
  pr-check:
    name: "Run Danger"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Danger
        uses: ./.github/actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
