on:
  pull_request:
    # masterブランチにマージする時に.sqlファイルが追加された場合にCircleCIのジョブを実行させて、CircleCIのジョブのリンクをPR画面に表示させる。
    branches:
      - master
    types: [ closed ]
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "say hello"
