on: 
 workflow_dispatch:
   inputs:
     logLevel:
       description: 'Log level'     
       required: true
       default: 'warning'
     some_string:
       description: 'なにかいれて'
       
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
       echo "Log level: ${{ github.event.inputs.logLevel }}"
       echo "Tags: ${{ github.event.inputs.some_string }}" 
       echo "actor: ${{ github.actor }}"
       echo "event: ${{ toJSON(github) }}"
    - uses: ./.github/steps_action
